"""initial_cva_schema

Revision ID: 3f19d8cf553d
Revises: 
Create Date: 2026-02-19 05:03:29.142772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f19d8cf553d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('account_number', sa.String(), nullable=True),
    sa.Column('pssr', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_external_id'), 'clients', ['external_id'], unique=True)
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('machines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('make', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('family', sa.String(), nullable=True),
    sa.Column('service_meter', sa.Float(), nullable=True),
    sa.Column('last_reported_time', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('last_visit', sa.String(), nullable=True),
    sa.Column('next_visit', sa.String(), nullable=True),
    sa.Column('psi_status', sa.String(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_machines_id'), 'machines', ['id'], unique=False)
    op.create_index(op.f('ix_machines_serial_number'), 'machines', ['serial_number'], unique=True)
    op.create_table('cvaf',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('start_date', sa.String(), nullable=True),
    sa.Column('end_date', sa.String(), nullable=True),
    sa.Column('cva_type', sa.String(), nullable=True),
    sa.Column('labor_type', sa.String(), nullable=True),
    sa.Column('country_code', sa.String(), nullable=True),
    sa.Column('product_vertical', sa.String(), nullable=True),
    sa.Column('dlr_cust_nm', sa.String(), nullable=True),
    sa.Column('current_asset_age', sa.Integer(), nullable=True),
    sa.Column('asset_age_group', sa.String(), nullable=True),
    sa.Column('inspection_score', sa.String(), nullable=True),
    sa.Column('connectivity_score', sa.String(), nullable=True),
    sa.Column('sos_score', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['serial_number'], ['machines.serial_number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cvaf_id'), 'cvaf', ['id'], unique=False)
    op.create_index(op.f('ix_cvaf_serial_number'), 'cvaf', ['serial_number'], unique=True)
    op.create_table('inspection_rate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('or_segment', sa.String(), nullable=True),
    sa.Column('type_materiel', sa.String(), nullable=True),
    sa.Column('atelier', sa.String(), nullable=True),
    sa.Column('date_facture', sa.String(), nullable=True),
    sa.Column('last_inspect', sa.String(), nullable=True),
    sa.Column('nbr', sa.Integer(), nullable=True),
    sa.Column('nom_client_or', sa.String(), nullable=True),
    sa.Column('is_inspected', sa.String(), nullable=True),
    sa.Column('technicien_reel', sa.String(), nullable=True),
    sa.Column('equipe_reelle', sa.String(), nullable=True),
    sa.Column('temps_reel', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['serial_number'], ['machines.serial_number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspection_rate_id'), 'inspection_rate', ['id'], unique=False)
    op.create_index(op.f('ix_inspection_rate_serial_number'), 'inspection_rate', ['serial_number'], unique=False)
    op.create_table('interventions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interventions_id'), 'interventions', ['id'], unique=False)
    op.create_index(op.f('ix_interventions_machine_id'), 'interventions', ['machine_id'], unique=False)
    op.create_index(op.f('ix_interventions_priority'), 'interventions', ['priority'], unique=False)
    op.create_index(op.f('ix_interventions_status'), 'interventions', ['status'], unique=False)
    op.create_index(op.f('ix_interventions_type'), 'interventions', ['type'], unique=False)
    op.create_table('remote_service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('flash_update', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['serial_number'], ['machines.serial_number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remote_service_id'), 'remote_service', ['id'], unique=False)
    op.create_index(op.f('ix_remote_service_serial_number'), 'remote_service', ['serial_number'], unique=True)
    op.create_table('suivi_ps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('client', sa.String(), nullable=True),
    sa.Column('reference_number', sa.String(), nullable=True),
    sa.Column('ps_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('action_required', sa.String(), nullable=True),
    sa.Column('deadline', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['serial_number'], ['machines.serial_number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suivi_ps_id'), 'suivi_ps', ['id'], unique=False)
    op.create_index(op.f('ix_suivi_ps_serial_number'), 'suivi_ps', ['serial_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_suivi_ps_serial_number'), table_name='suivi_ps')
    op.drop_index(op.f('ix_suivi_ps_id'), table_name='suivi_ps')
    op.drop_table('suivi_ps')
    op.drop_index(op.f('ix_remote_service_serial_number'), table_name='remote_service')
    op.drop_index(op.f('ix_remote_service_id'), table_name='remote_service')
    op.drop_table('remote_service')
    op.drop_index(op.f('ix_interventions_type'), table_name='interventions')
    op.drop_index(op.f('ix_interventions_status'), table_name='interventions')
    op.drop_index(op.f('ix_interventions_priority'), table_name='interventions')
    op.drop_index(op.f('ix_interventions_machine_id'), table_name='interventions')
    op.drop_index(op.f('ix_interventions_id'), table_name='interventions')
    op.drop_table('interventions')
    op.drop_index(op.f('ix_inspection_rate_serial_number'), table_name='inspection_rate')
    op.drop_index(op.f('ix_inspection_rate_id'), table_name='inspection_rate')
    op.drop_table('inspection_rate')
    op.drop_index(op.f('ix_cvaf_serial_number'), table_name='cvaf')
    op.drop_index(op.f('ix_cvaf_id'), table_name='cvaf')
    op.drop_table('cvaf')
    op.drop_index(op.f('ix_machines_serial_number'), table_name='machines')
    op.drop_index(op.f('ix_machines_id'), table_name='machines')
    op.drop_table('machines')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_external_id'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
